Tables and Fields:

 book

- book_id — INTEGER (Primary Key)

- title — TEXT NOT NULL

- author — TEXT

- price — REAL

member

- member_id — INTEGER (Primary Key)

- name — TEXT NOT NULL

- email — TEXT NOT NULL

 borrow

- borrow_id — INTEGER (Primary Key)

- member_id — INTEGER (Foreign Key)

- borrow_date — TEXT NOT NULL

 borrow_item

- borrow_id — INTEGER (Foreign Key)

- book_id — INTEGER (Foreign Key)

- quantity — INTEGER

Instructions:

In [ ]:
#Q1 - Create SQLite Database library.db with  4 tables exactly as defined above.

In [ ]:
#Q2 -  Load CSV Data into Tables

#Use these datasets:

book_url = "https://drive.google.com/uc?id=15VJe4cPZdMDIBgX1ZCT2CSDkoCGpsOJy"

member_url = "https://drive.google.com/uc?export=download&id=1BEBIICEF-0bIbn3TkwDLlAzVNsJXXbri"

borrow_url = "https://drive.google.com/uc?export=download&id=1cGJuylPG5RgK4Qx9VuikM0mViRtpu4cS"

borrow_item_url = "https://drive.google.com/uc?export=download&id=12OKCuhEi6Z7nTAdjS-wv4Nog_n2lsIx1"

In [1]:
#Q3 -  Commit Changes

import pandas as pd
b=pd.read_csv(book_url)
b

ModuleNotFoundError: No module named 'pandas'

In [ ]:
m=pd.read_csv(member_url)
m

   member_id     name              email
0        101    Alice    alice@email.com
1        102      Bob      bob@email.com
2        103  Charlie  charlie@email.com
3        104    Diana    diana@email.com

In [ ]:
bor=pd.read_csv(borrow_url)
bor

   borrow_id  member_id borrow_date
0        201        101  2024-03-01
1        202        102  2024-03-02
2        203        103  2024-03-03
3        204        101  2024-03-05

In [ ]:
bori=pd.read_csv(borrow_item_url)
bori

   borrow_id  book_id  quantity
0        201        1         1
1        201        2         2
2        202        3         1
3        203        4         1
4        204        5         3

In [ ]:
#Q4 - Verify all Tables e.g.SELECT * FROM book;


#Display results.

In [ ]:
#Q5 - JOIN Query

#Find:member name, borrow date, book title, quantity for each borrowed book.

In [ ]:
#Q6 - Filtered JOIN Query

#Find: All books borrowed by a specific member. Example: member name = 'Alice'